# Generated by Django 5.2.17 on 2026-08-19 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Tên tiện nghi')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang cung cấp')),
            ],
            options={
                'verbose_name': 'Tiện nghi',
                'verbose_name_plural': 'Tiện nghi',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Tên loại phòng')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã loại')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('max_guests', models.PositiveSmallIntegerField(default=2, verbose_name='Số khách tối đa')),
                ('area_sqm', models.PositiveSmallIntegerField(default=25, verbose_name='Diện tích (m²)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang kinh doanh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Loại phòng',
                'verbose_name_plural': 'Loại phòng',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Tên dịch vụ')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá niêm yết')),
                ('unit', models.CharField(default='lần', max_length=50, verbose_name='Đơn vị tính')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang cung cấp')),
            ],
            options={
                'verbose_name': 'Dịch vụ',
                'verbose_name_plural': 'Dịch vụ',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=180, verbose_name='Hoạt động')),
                ('level', models.CharField(choices=[('INFO', 'Thông tin'), ('WARNING', 'Cảnh báo'), ('SUCCESS', 'Thành công')], default='INFO', max_length=20, verbose_name='Mức độ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Nhật ký hoạt động',
                'verbose_name_plural': 'Nhật ký hoạt động',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá/đêm')),
                ('valid_from', models.DateField(verbose_name='Áp dụng từ')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Áp dụng đến')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='admin_panel.roomtype', verbose_name='Loại phòng')),
            ],
            options={
                'verbose_name': 'Giá phòng',
                'verbose_name_plural': 'Giá phòng',
                'ordering': ('-valid_from',),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Số phòng')),
                ('floor', models.PositiveSmallIntegerField(default=1, verbose_name='Tầng')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Còn trống'), ('BOOKED', 'Đã đặt'), ('OCCUPIED', 'Đang sử dụng'), ('MAINTENANCE', 'Đang bảo trì')], default='AVAILABLE', max_length=20, verbose_name='Tình trạng')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='admin_panel.roomtype', verbose_name='Loại phòng')),
            ],
            options={
                'verbose_name': 'Phòng',
                'verbose_name_plural': 'Phòng',
                'ordering': ('number',),
            },
        ),
    ]
