# Generated by Django 5.2.17 on 2026-08-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomtype",
            name="amenities",
            field=models.ManyToManyField(
                blank=True,
                related_name="room_types",
                to="admin_panel.amenity",
                verbose_name="Tiện nghi",
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="image_url",
            field=models.URLField(blank=True, verbose_name="Ảnh phòng"),
        ),
    ]
