# Generated by Django 5.2.17 on 2026-09-03 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_roomtype_amenities_roomtype_image_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="roomprice",
            name="unit",
            field=models.CharField(
                choices=[("NIGHT", "Theo đêm"), ("HOUR", "Theo giờ")],
                default="NIGHT",
                max_length=10,
                verbose_name="Đơn vị tính",
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="room_listings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Nhân viên đăng",
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="listing_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Chờ duyệt"),
                    ("PUBLISHED", "Đã duyệt"),
                    ("REJECTED", "Từ chối"),
                ],
                default="PUBLISHED",
                max_length=20,
                verbose_name="Trạng thái đăng bán",
            ),
        ),
        migrations.CreateModel(
            name="RoomImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        upload_to="room-listings/", verbose_name="Hình ảnh"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="admin_panel.roomtype",
                        verbose_name="Loại phòng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ảnh phòng",
                "verbose_name_plural": "Ảnh phòng",
                "ordering": ("uploaded_at",),
            },
        ),
    ]
