# Generated by Django 5.2.17 on 2026-09-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_roomprice_unit_roomtype_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomtype",
            name="image_url",
            field=models.ImageField(
                blank=True, upload_to="room-listings/", verbose_name="Ảnh phòng"
            ),
        ),
    ]
