# Generated by Django 5.2.17 on 2026-09-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0004_alter_roomtype_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomimage",
            name="image",
            field=models.ImageField(
                upload_to="room-listings/", verbose_name="Hình ảnh"
            ),
        ),
    ]
