# Generated by Django 5.2.17 on 2026-09-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0006_roomtype_is_under_maintenance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Còn trống"),
                    ("DEPOSIT", "Đang đặt cọc"),
                    ("BOOKED", "Đã đặt"),
                    ("OCCUPIED", "Đang sử dụng"),
                    ("MAINTENANCE", "Đang bảo trì"),
                ],
                default="AVAILABLE",
                max_length=20,
                verbose_name="Tình trạng",
            ),
        ),
    ]
