# Generated by Django 5.2.17 on 2026-08-19 12:33

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts.models.LuminaUserManager()),
            ],
        ),
    ]
