# Generated by Django 5.2.17 on 2026-08-19 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_consultationrequest_booking"),
        ("admin_panel", "0002_roomtype_amenities_roomtype_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="admin_panel.room",
                verbose_name="Phòng",
            ),
        ),
    ]
