# Generated by Django 5.2.17 on 2026-09-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_booking_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="guest_full_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Họ và tên khách"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="guest_id_number",
            field=models.CharField(blank=True, max_length=20, verbose_name="CCCD/CMND"),
        ),
        migrations.AddField(
            model_name="booking",
            name="guest_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Số điện thoại khách"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Chờ xác nhận"),
                    ("CONFIRMED", "Đã xác nhận"),
                    ("CANCELLED", "Đã hủy"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
