# Generated by Django 5.2.17 on 2026-09-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_booking_guest_full_name_booking_guest_id_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Chờ xác nhận"),
                    ("CONFIRMED", "Đã xác nhận"),
                    ("CHECKED_IN", "Đã check-in"),
                    ("CANCELLED", "Đã hủy"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
