# Generated by Django 5.2.17 on 2026-09-05 03:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="check_in_time",
            field=models.TimeField(default="14:00"),
        ),
        migrations.AddField(
            model_name="booking",
            name="check_out_time",
            field=models.TimeField(default="12:00"),
        ),
        migrations.AddField(
            model_name="booking",
            name="id_card_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="booking-id-cards/",
                verbose_name="Ảnh CCCD",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="qr_token",
            field=models.UUIDField(default=None, editable=False, null=True),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _populate_qr_tokens(apps),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="booking",
            name="qr_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Chờ xác nhận"),
                    ("CONFIRMED", "Đã xác nhận"),
                    ("CHECKED_IN", "Đã check-in"),
                    ("CHECKED_OUT", "Đã check-out"),
                    ("CANCELLED", "Đã hủy"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CheckInRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Chờ staff xác nhận"),
                            ("APPROVED", "Đã xác nhận check-in"),
                            ("REJECTED", "Đã từ chối"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("staff_note", models.TextField(blank=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_in_request",
                        to="accounts.booking",
                    ),
                ),
            ],
            options={
                "ordering": ("-requested_at",),
            },
        ),
    ]


def _populate_qr_tokens(apps):
    Booking = apps.get_model("accounts", "Booking")
    for booking in Booking.objects.filter(qr_token__isnull=True).iterator():
        booking.qr_token = uuid.uuid4()
        booking.save(update_fields=("qr_token",))
