# Generated by Django 5.2.17 on 2026-09-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_booking_check_in_time_booking_check_out_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="id_card_image",
            new_name="id_card_front_image",
        ),
        migrations.AddField(
            model_name="booking",
            name="id_card_back_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="booking-id-cards/",
                verbose_name="Ảnh CCCD mặt sau",
            ),
        ),
    ]
