# Generated by Django 5.2.17 on 2026-09-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_booking_id_card_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="id_card_front_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="booking-id-cards/",
                verbose_name="Ảnh CCCD mặt trước",
            ),
        ),
    ]
