# Generated by Django 5.2.17 on 2026-09-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_booking_id_card_front_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="paid_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Thời điểm thanh toán"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_reference",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Mã giao dịch"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("UNPAID", "Chưa thanh toán"),
                    ("PENDING", "Chờ xác nhận thanh toán"),
                    ("PAID", "Đã thanh toán"),
                    ("REJECTED", "Thanh toán bị từ chối"),
                ],
                default="UNPAID",
                max_length=20,
                verbose_name="Trạng thái thanh toán",
            ),
        ),
    ]
