# Generated by Django 5.2.17 on 2026-09-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_booking_paid_at_booking_payment_reference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="momo_order_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="MoMo order ID"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="momo_request_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="MoMo request ID"
            ),
        ),
    ]
