# Generated by Django 5.2.17 on 2026-09-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_booking_momo_order_id_booking_momo_request_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_proof",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="payment-proofs/",
                verbose_name="Ảnh biên lai thanh toán",
            ),
        ),
    ]
