# Generated by Django 5.2.17 on 2026-09-17 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_remove_chatmessage_conversation_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatroom",
            options={},
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="customer_name",
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="customer_phone",
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="session_key",
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="staff",
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="chatroom",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
