# Generated by Django 5.2.17 on 2026-09-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_remove_chatroom_user_chatroom_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="customer_name",
            field=models.CharField(
                blank=True, default="Khách vãng lai", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="customer_phone",
            field=models.CharField(blank=True, default="Chưa có", max_length=50),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="session_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
