# Generated by Django 5.2.17 on 2026-09-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_chatroom_customer_name_chatroom_customer_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="mode",
            field=models.CharField(
                choices=[("BOT", "Chatbot tự động"), ("STAFF", "Nhân viên hỗ trợ")],
                default="BOT",
                max_length=20,
            ),
        ),
    ]
