# Generated by Django 5.2.17 on 2026-09-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_chatroom_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatbotFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        default="GENERAL", max_length=50, verbose_name="Phân loại"
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        help_text="Phân cách bằng dấu phẩy, ví dụ: deluxe, tiện ích, giá phòng",
                        max_length=255,
                        verbose_name="Từ khóa nhận diện",
                    ),
                ),
                (
                    "question",
                    models.CharField(max_length=255, verbose_name="Câu hỏi mẫu"),
                ),
                ("answer", models.TextField(verbose_name="Câu trả lời")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang sử dụng"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Hỏi đáp Chatbot (FAQ)",
                "verbose_name_plural": "Hỏi đáp Chatbot (FAQ)",
                "ordering": ["category", "id"],
            },
        ),
    ]
